//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeMngWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityDetail
    {
        public int City_id { get; set; }
        public string CityName { get; set; }
        public Nullable<int> Status_id { get; set; }
    }
}
