//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeMngWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public int Desig_id { get; set; }
        public string DesigType { get; set; }
        public string DesigDesc { get; set; }
    }
}
